# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = de
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

gesture = 3, horizontal, workspace

general {
    layout = dwindle
    allow_tearing = false
}

dwindle {
    preserve_split = yes
}

# Dealing with edge cases and the likes
windowrule = match:class .*, suppress_event maximize # You'll probably like this.
windowrule = match:class zen, match:title .*YouTube.*, opacity 1,

windowrule = match:class thunderbird, float on
windowrule = match:class thunderbird, match:initial_title Mozilla Thunderbird, tile on # deal with thunderbird popup
windowrule = match:class swayimg, float on
