{ inputs, ... }:
{
  imports = [
    inputs.dod-shell.homeManagerModules.default
    ./awww.nix
    ./btop.nix
    ./cava.nix
    ./cursor.nix
    ./dev.nix
    ./dev.nix
    ./dod-shell.nix
    ./fastfetch.nix
    ./fonts.nix
    ./hypr.nix
    ./igneous-md.nix
    ./mime.nix
    ./mpv.nix
    ./office.nix
    ./shell
    ./spotify-player.nix
    ./swayimg.nix
    ./syncthing.nix
    ./term
    ./vesktop.nix
    ./yazi.nix
    ./zathura.nix
    ./zen.nix
  ];
}
